spring.application.name=inventory-backend
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/devconnect_db
spring.datasource.username=root
spring.datasource.password=root@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
